name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate Skyline
        run: |
          curl -L "https://skyline.github.com/${{ github.repository_owner }}/2024.svg" -o skyline.svg

      - name: Check for Changes
        run: |
          if git diff --quiet skyline.svg; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Commit & Push
        if: success()  # Only run if there are changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add skyline.svg
          git commit -m "Atualizar skyline 3D"
          git push
