name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate Skyline
        run: |
          curl -L "https://skyline.github.com/${{ github.repository_owner }}/2024.svg" -o skyline.svg

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add skyline.svg
          git commit -m "Atualizar skyline 3D"
          git push
