name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate Skyline
        run: |
          curl -L "https://skyline.github.com/${{ github.repository_owner }}/2024.svg" -o skyline.svg
          if [ ! -s skyline.svg ]; then
            echo "Error: Failed to download skyline.svg or file is empty."
            exit 1
          fi

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add skyline.svg
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Atualizar skyline 3D"
          git push
